# Generated by Django 6.0.3 on 2026-03-10 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('soil_moisture', 'Soil Moisture (%)'), ('air_temp', 'Air Temp (°C)'), ('humidity', 'Humidity (%)'), ('ph', 'pH')], max_length=32)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='farms.farm')),
            ],
        ),
    ]
