# Generated by Django 6.0.3 on 2026-03-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_type',
            field=models.CharField(choices=[('soil_moisture', 'Soil Moisture (%)'), ('air_temp', 'Air Temp (°C)'), ('humidity', 'Humidity (%)')], max_length=32),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='unit',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
