# Generated by Django 6.0.3 on 2026-03-23 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField(help_text='Soil moisture (%) entered by farmer or from sensor')),
                ('month', models.IntegerField(help_text='1-12')),
                ('irrigation', models.BooleanField(default=False)),
                ('top_crop', models.CharField(max_length=120)),
                ('results_json', models.JSONField(help_text='Top N recommendations with scores/reasons')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['farm', 'created_at'], name='dashboard_a_farm_id_d4cad7_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'created_at'], name='dashboard_a_severit_d4b835_idx'),
        ),
        migrations.AddField(
            model_name='croprecommendation',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_recommendations', to='farms.farm'),
        ),
        migrations.AddIndex(
            model_name='croprecommendation',
            index=models.Index(fields=['farm', 'created_at'], name='dashboard_c_farm_id_6a4388_idx'),
        ),
    ]
